project:
  type: website
  output-dir: docs

website:
  title: "気楽にウェブサイト"
  google-analytics: "G-LLFB8XFPX5"
  navbar:
    left:
      - get-started.qmd

format:
  html:
    theme:
      - materia
      - custom.scss
    include-in-header: font.html
    mainfont: Noto Sans JP, Helvetica Neue, Arial, Hiragino Kaku Gothic ProN, Hiragino Sans, BIZ UDPGothic, Meiryo, sans-serif
    link-external-newwindow: true
    toc: true
    toc-title: " "
    number-sections: true

lang: ja
